ADONET MVC PROJECT/Models/employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace ADONET_MVC_PROJECT.Models
{
    public class employee
    {
        public int empno { get; set; }
        public string empnam { get; set; }
        public int empsal { get; set; }
        public string empadd { get; set; }
    }

    public abstract class clscon
    {
        protected SqlConnection con = new SqlConnection();
        public clscon()
        {
            con.ConnectionString = ConfigurationManager.ConnectionStrings["cn"].ConnectionString;
        }
    }
}

ADONET MVC PROJECT/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ADONET_MVC_PROJECT.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ADONET MVC PROJECT/Controllers/employeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ADONET_MVC_PROJECT.DAL;
using ADONET_MVC_PROJECT.Models;


using System.Configuration;


namespace ADONET_MVC_PROJECT.Controllers
{
    public class employeeController : Controller
    {
        employeerepository rep = new employeerepository();
        // GET: employee
        public ActionResult Index()
        {
           
            var list = rep.Disp_Rec();

            return View(list);
        }

        // GET: employee/Details/5
        public ActionResult Details(int id)
        {
            
                var sss = rep.Find_Rec(id);
                return View(sss);
            
           
        }

        // GET: employee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: employee/Create
        [HttpPost]
        public ActionResult Create(employee emp)
        {
            try
            {
                rep.Save_Rec(emp);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: employee/Edit/5
        public ActionResult Edit(int id)
        {
            var sss = rep.Find_Rec(id);
            return View(sss);
        }

        // POST: employee/Edit/5
        [HttpPost]
        public ActionResult Edit(employee emp)
        {
            try
            {
                rep.Update_Rec(emp);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: employee/Delete/5
        public ActionResult Delete(int id)
        {
            return View(rep.Find_Rec(id));
        }

        // POST: employee/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, employee emp)
        {
            try
            {
                rep.Delete_Rec(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ADONET MVC PROJECT/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ADONET MVC PROJECT/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ADONET MVC PROJECT/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ADONET MVC PROJECT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Employee", "Index", "employee")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ADONET MVC PROJECT/Views/employee/Create.cshtml
@model ADONET_MVC_PROJECT.Models.employee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.empno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.empno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.empno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.empnam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.empnam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.empnam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.empsal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.empsal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.empsal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.empadd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.empadd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.empadd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ADONET MVC PROJECT/Views/employee/Delete.cshtml
@model ADONET_MVC_PROJECT.Models.employee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.empno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empnam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empnam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empsal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empsal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empadd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empadd)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ADONET MVC PROJECT/Views/employee/Details.cshtml
@model ADONET_MVC_PROJECT.Models.employee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.empno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empnam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empnam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empsal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empsal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.empadd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empadd)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ADONET MVC PROJECT/Views/employee/Edit.cshtml
@model  ADONET_MVC_PROJECT.Models.employee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <h4>employee</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.empno, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empno, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empno, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.empnam, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empnam, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empnam, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.empsal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empsal, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empsal, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.empadd, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.empadd, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.empadd, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

ADONET MVC PROJECT/Views/employee/Index.cshtml
@model IEnumerable<ADONET_MVC_PROJECT.Models.employee>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.empno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.empnam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.empsal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.empadd)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.empno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.empnam)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.empsal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.empadd)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id =item.empno }) |
            @Html.ActionLink("Details", "Details", new { id=item.empno}) |
            @Html.ActionLink("Delete", "Delete", new { id=item.empno })
        </td>
    </tr>
}

</table>